name: Workflow - Practicing Github Actions
on:
  push:
    tags: v1.2
env:
  GREETING: ${{secrets.GREETING}}
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      GREETING: "Hello tag v1.2"
    steps:
      - name: Step 1
        run: echo $GREETING
